### ISSUE TITLE
Coverage report does not work with modules included with 'rewire'

### ISSUE THREAD

**Issue by mghaderyan** [duereg/gulp-coffee-istanbul#2]
When using rewire (https://github.com/jhnns/rewire) the report considers zero percent of coverage. for example if I am testing myModule.cofee and in myModule.spec.cofee I am doing this: 
myModule = rewire 'src/myModule' 
instead of myModule = require 'src/myModule' 

The coverage report thinks there is no test for myModule. Is there a way to fix this?
Thanks

**Comment by duereg** [comment]
This isn't a bug with either system - it's more a problem with how rewire patches require. 

From the rewire docs:

Difference to require()
------------------------------
Every call of rewire() executes the module again and returns a fresh instance.

```javascript
rewire("./myModule.js") === rewire("./myModule.js"); // = false
```

For code coverage to work, you need to instrument a file, and then use that file over and over again (to determine which methods were called). 

It appears the method that rewire would prevent this approach (which would prevent any code coverage tool from working, IMO).

So no way to "fix" this.
