### ISSUE TITLE
node_modules not checked in

### ISSUE THREAD

**Issue by jonwalstedt** [duereg/gulp-coffee-istanbul#3]
Seems like the node_modules for this package is not checked in forcing you to do a separate npm install for this package

**Comment by duereg** [comment]
That's pretty standard... you don't check in node_modules, and on doing an npm install, it will install the modules for you. 

Just try `npm install gulp-coffee-istanbul` and that should install all the files you need. 

Hope this helps!

**Comment by jonwalstedt** [comment]
Hmm yeah i know, bit i got a little confused about it because it wasn't working. I ran npm install on the project where i use this module an it looked everything went fine (no errors or warnings during install) then afterwards it conplained when i ran gulp that the dependencies for this plugin was not installed. Any who, it worked after completely removing the node_modules folder and reinstall. 



—
